
# This is a template Makefile generated by rpcgen

# Parameters

CLIENT = server
SERVER = server_rpc

SOURCES_CLNT.c = 
SOURCES_CLNT.h = 
SOURCES_SVC.c = 
SOURCES_SVC.h = 
SOURCES.x = log.x

TARGETS_SVC.c = log_svc.c server_rpc.c log_xdr.c 
TARGETS_CLNT.c = log_clnt.c server.c log_xdr.c funciones.c comm.c
TARGETS = log.h log_xdr.c log_clnt.c log_svc.c log_client.c log_server.c


OBJECTS_CLNT = $(SOURCES_CLNT.c:%.c=%.o) $(TARGETS_CLNT.c:%.c=%.o)
OBJECTS_SVC = $(SOURCES_SVC.c:%.c=%.o) $(TARGETS_SVC.c:%.c=%.o)
# Compiler flags 

CC = gcc
CFLAGS = -g -I. -I/usr/include/tirpc -Wall -Wno-unused-variable
LDLIBS = -lnsl -lpthread -ldl -ltirpc
RPCGENFLAGS = -a -N -M

# Targets 

all : $(CLIENT) $(SERVER)

$(TARGETS) : $(SOURCES.x) 
	rpcgen $(RPCGENFLAGS) $(SOURCES.x)

.o: %.c
	$(CC) $(CFLAGS) -c $< -o $@

$(CLIENT) : $(OBJECTS_CLNT) 
	$(CC) -o $(CLIENT) $(OBJECTS_CLNT) $(LDLIBS) $(CFLAGS)

$(SERVER) : $(OBJECTS_SVC) 
	$(CC) -o $(SERVER) $(OBJECTS_SVC) $(LDLIBS) $(CFLAGS)

 clean:
	 $(RM) core $(TARGETS) $(OBJECTS_CLNT) $(OBJECTS_SVC) $(CLIENT) $(SERVER) Makefile.log

