/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "log.h"
#include <stdio.h>
#include <string.h>

bool_t
send_log_1_svc(struct log_msg log, int *result,  struct svc_req *rqstp)
{
	bool_t retval = TRUE;

	if (strcmp(log.op_log, "PUBLISH") == 0 || strcmp(log.op_log, "DELETE") == 0){ // Si la operacion es PUBLISH o DELETE, se imprime junto con el nombre del archivo
		printf("%s %s %s %s %s\n", 
		log.user_log, log.op_log, log.file_name_log, log.date_log, log.time_log);
		*result = 0;
		
	} else { // Si no, se imprime sin el nombre del archivo
		printf("%s %s %s %s\n", 
		log.user_log, log.op_log, log.date_log, log.time_log);
		*result = 0;
	}
	

	return retval;
}

int
log_1_freeresult (SVCXPRT *transp, xdrproc_t xdr_result, caddr_t result)
{
	xdr_free (xdr_result, result);

	/*
	 * Insert additional freeing code here, if needed
	 */

	return 1;
}
